config/routes.rb
Rails.application.routes.draw do
  resources :links
  devise_for :users, :controllers => {
    registrations: 'registrations'
  }
  root "main#home"
  resources :users, only: [:index, :create, :new, :destroy, :show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "l/:slug" => "links#send_to_original_url", as: :send_to_original_url
  post "l/:slug" => "links#authenticate_private_link", as: :authenticate_private_link
  get "links/:id/daily_access_count_report" => "links#daily_access_count_report", as: :daily_access_count_report_links
  get "links/:id/access_detail_report" => "links#access_detail_report", as: :access_detail_report_links

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/LinkAccess.rb
class LinkAccess < ApplicationRecord
    belongs_to :link
    scope :by_day, -> { group_by_day(:access_time).count }

    def self.ransackable_attributes(auth_object = nil)
        ["access_time", "created_at", "id", "id_value", "ip_address", "link_id", "updated_at"]
      end

    def self.create_access(link, current_time, ip_address)
      create(link: link, access_time: current_time, ip_address: ip_address)
    end


end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :user
  has_many :link_accesses, dependent: :destroy
  validates :name, presence: false
  validates :slug, uniqueness: true
  validates :link_category, presence: true
  validates :expires_at, presence: true , if: :temporary?
  validates :password, presence: true , if: :private_link?
  validates :url, presence: true ,format: { with: URI.regexp }
  has_secure_password validations: false

  enum link_category: { regular: 'regular', temporary: 'temporary', private_link: 'private_link', ephemeral: 'ephemeral' }

  before_validation :generate_slug_and_unique_url, on: :create
  
  

  def self.update_single_use
    update(single_use: true)
  end  

  private
  def generate_slug_and_unique_url
    self.slug ||= SecureRandom.hex(3)
  end
  def temporary?
    link_category == 'temporary'
  end

  def private_link?
    link_category == 'private_link'
  end



end


  

app/models/user.rb
class User < ApplicationRecord

  has_many :links , dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: { case_sensitive: false }    
      

 def get_username
   return self.username
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def not_found
       render file: "#{Rails.root}/app/views/errors/404.html", layout: false, status: :not_found
    end

    def forbidden
        render file: "#{Rails.root}/app/views/errors/403.html", layout: false, status: :forbidden
    end

end

    

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[send_to_original_url authenticate_private_link]


  # GET /links or /links.json
  def index
    """
    Listado de links paginados , usando gema will_paginate
    """
    @links = current_user.links.paginate(page: params[:page], per_page: 4)
  end
  
  

  # GET /links/1 or /links/1.json
  def show
    @link = Link.find(params[:id])
    @short = send_to_original_url_url(@link.slug) 
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.build(link_params)
    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: 'Link was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: 'Link was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
    end
  end


def send_to_original_url
  @link = Link.find_by(slug: params[:slug])
  if @link.present?
    case @link.link_category
    when 'private_link'
      render 'send_to_url_with_password'
    when 'temporary'
      redirect_temporary_link
    when 'ephemeral'
      redirect_ephemeral_link
    else
      redirect_default_link
    end
  else
    flash[:alert] = 'Link not found'
    redirect_to root_path
  end
end

def authenticate_private_link
  @link = Link.find_by(slug: params[:slug])

  if @link.present? && @link.authenticate(params[:password])
    LinkAccess.create_access(@link, current_time, request.remote_ip)
    redirect_to @link.url, allow_other_host: true
  else
    flash[:alert] = 'Invalid password'
    render 'send_to_url_with_password'
  end
end


def access_detail_report
  """ 
  Detalle de accesos por link usando gema ransack para filtrar
  """
    @link = Link.find(params[:id]) 
    @q = @link.link_accesses.ransack(params[:q])
    @acces = @q.result.paginate(page: params[:page], per_page: 6)
end
  

def daily_access_count_report
  """ 
  Lógica para mostrar el listado de accesos por día
  """
  @link = Link.find(params[:id]) 
  if @link.link_accesses.present?
    @access_counts_by_day = @link.link_accesses.by_day
    @access_counts_by_day.reject! { |day, count| count.zero? }
  else
    @access_counts_by_day = {}
  end
end




private

  def authorize_user!
    unless current_user == @link.user
      forbidden
    end
  end

  def current_time
    DateTime.now.strftime("%Y-%m-%d %H:%M:%S")
  end  


  def redirect_temporary_link
    if @link.expires_at > current_time
      LinkAccess.create_access(@link, current_time, request.remote_ip)
      redirect_to @link.url, allow_other_host: true
    else
      not_found
    end
  end
  
  
  def redirect_ephemeral_link
    if !@link.single_use?
      Link.update_single_use
      LinkAccess.create_access(@link, current_time, request.remote_ip)
      redirect_to @link.url, allow_other_host: true
    else
      forbidden
    end
  end
  
  
  def redirect_default_link
    LinkAccess.create_access(@link, current_time, request.remote_ip)
    redirect_to @link.url, allow_other_host: true
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def link_params
    if params[:link].present?
      permitted_params =  [:url,:name, :link_category, :expires_at,:password]
      params.require(:link).permit(permitted_params)
    end
  end 
  
  
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
def home
end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
      def sign_up_params
        params.require(:user).permit(:email, :password, :username)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!         
  def index
  end

  def create
  end

  def new
  end

  def destroy
    @user.destroy!
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inicio de sesión</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <link rel="preload" as="script" href="https://code.jquery.com/jquery-3.6.0.min.js">

  </head>

  <body>
     <%= render 'main/header'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>
      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Common form fields -->
  <div class="form-group">
    <%= form.label :url %>
    <%= form.text_field :url, class: 'form-control' %>
  </div>

<div class="form-group">
  <%= form.label :name do %>
    <%= "Name (opcional)" %>
  <% end %>
  <%= form.text_field :name, class: 'form-control' %>
</div>

  <div class="form-group">
    <%= form.label :link_category %>
    <%= form.select :link_category, Link.link_categories.keys, {}, class: 'form-control link-category-select' %>
  </div>

  <!-- Additional fields based on link type -->
  <div id="temporary-fields" style="display: none;">
    <div class="form-group">
      <%= form.label :expires_at %>
      <%= form.datetime_field :expires_at, class: 'form-control' %>
    </div>
  </div>

  <div id="private-fields" style="display: none;">
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, autocomplete: "current-password", class: 'form-control' %>
    </div>
  </div>

  <!-- Submit button -->
  <div class="form-group">
  <br>
    <%= form.submit link.persisted? ? "Update Link" : "Create Link", class: "btn btn-primary" %>
  </div>

  <script>
    $(document).ready(function () {
      var linkCategorySelect = $('.link-category-select');
      var temporaryFields = $('#temporary-fields');
      var privateFields = $('#private-fields');

      linkCategorySelect.change(function () {
        var selectedCategory = linkCategorySelect.val();
        console.log('Selected Category:', selectedCategory);

        temporaryFields.toggle(selectedCategory === 'temporary');
        privateFields.toggle(selectedCategory === 'private_link');
      });
    });
  </script>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
</div>

app/views/links/access_detail_report.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Access Details</h1>

  <%= search_form_for @q, url: access_detail_report_links_path, html: { class: 'mb-4' } do |f| %>
    <div class="row g-3">
      <div class="col-md-4">
        <%= f.label :ip_address_cont, 'Filter by IP Address:', class: 'form-label' %>
        <%= f.search_field :ip_address_cont, class: 'form-control' %>
      </div>

      <div class="col-md-4">
        <%= f.label :access_time_gteq, 'Filter from date:', class: 'form-label' %>
        <%= f.datetime_local_field :access_time_gteq, class: 'form-control' %>
      </div>

      <div class="col-md-4">
        <%= f.label :access_time_lteq, 'Filter until date:', class: 'form-label' %>
        <%= f.datetime_local_field :access_time_lteq, class: 'form-control' %>
      </div>

      <div class="col-12">
        <%= f.submit 'Filter', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped mt-4">
      <thead>
        <tr>
          <th scope="col">Date and Time</th>
          <th scope="col">IP Address</th>
          <!-- Add other columns as needed -->
        </tr>
      </thead>
      <tbody>
        <% if @acces.present? %>
          <% @acces.each do |access| %>
            <tr>
              <td><%= access.access_time %></td>
              <td><%= access.ip_address %></td>
              <!-- Add other columns as needed -->
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="2">No results found</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="text-center">
    <%= will_paginate @acces, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/links/daily_access_count_report.html.erb
<!-- app/views/links/daily_access_count_report.html.erb -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Reporte de Accesos Diarios</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    body {
      background-color: #f8f9fa;
    }

    .container {
      background-color: #ffffff;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
      border-radius: 15px;
      padding: 30px;
      margin-top: 50px;
    }

    h1 {
      color: #007bff;
      margin-bottom: 30px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    th, td {
      padding: 20px;
      text-align: left;
      border-bottom: 1px solid #dee2e6;
    }

    th {
      background-color: #007bff;
      color: #ffffff;
    }
  </style>
</head>
<body>

<div class="container">
  <h1>Daily Access Report</h1>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Day</th>
        <th scope="col">Access Count</th>
      </tr>
    </thead>
    <tbody>
      <% @access_counts_by_day.each do |day, count| %>
          <tr>
            <td><%= day %></td>
            <td><%= count %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!-- Bootstrap JS (optional, for some functionalities) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/links/edit.html.erb
<div class="container mt-4">
  <h1 class="mb-4">Editing Link</h1>

  <%= render "form", link: @link %>

  <div class="mt-3">
    <br>
    <%= link_to "Show this link", @link, class: "btn btn-primary" %> |
    <%= link_to "Back to links", links_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/links/index.html.erb
<div class="container mt-4">
  <% if notice.present? %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <h1 class="mb-4">Links Management</h1>

  <div class="card">
    <div class="card-header bg-primary text-white">
      <h4 class="mb-0">Link Details</h4>
    </div>

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover">
         <thead>
            <tr>
              <th>Original URL</th>
              <th>Shortened URL</th>
              <th>Category</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
          <% @links.each do |link| %>
            <tr>
              <td><%= link.url %></td>
              <td><%= link.slug %></td>
              <td><%= link.link_category %></td>
              <td>
                <%= link_to "Show", link, class: "btn btn-primary btn-sm mr-1" %>
                <%= button_to "Destroy", link, method: :delete, class: "btn btn-danger btn-sm", onclick: "return confirm('Are you sure?');", form_class: "d-inline" %>
                <%= link_to "Edit", edit_link_path(link), class: "btn btn-warning btn-sm mr-1" %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
      <div class="text-center">
        <%= will_paginate @link, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
    </div>
  </div>

  <div class="mt-3">
    <%= link_to "New link", new_link_path, class: "btn btn-success" %>
  </div>
</div>

app/views/links/new.html.erb
<div class="container mt-5">
  <h1>New Link</h1>

  <%= render "form", link: @link %>

  <div class="mt-3">
    <%= link_to "Back to Links", links_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/links/send_to_url_with_password.html.erb
<h2>Enter password to access this link</h2>

<%= form_tag(authenticate_private_link_path(params[:slug]), method: :post, class: "mt-4") do %>
  <div class="form-group">
    <% if flash[:alert].present? %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:alert] %>
    </div>
   <% end %>
    <%= label_tag(:password, "Password:") %>
    <%= password_field_tag(:password, nil, class: "form-control") %>
  </div>
  <br>
  <%= submit_tag('Send', class: 'btn btn-primary') %>
<% end %>

app/views/links/show.html.erb
<div class="container mt-4">
  <% if notice.present? %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <%= render @link %>

  <div class="card mt-3">
    <div class="card-body">
      <h2 class="card-title">Share this link</h2>
      <p class="card-text"><%= link_to send_to_original_url_url(@link.slug) ,send_to_original_url_url(@link.slug),  class: "btn btn-primary" %></p>
      <% if @link.link_category == "temporary" %>
        <p class="card-text">This link will be expired at <%= @link.expires_at %></p>
     <% end %>  
    </div>
  </div>
  <div class="mt-3">
    <%= link_to "Report", daily_access_count_report_links_path(@link), class: "btn btn-success btn-sm mr-1" %>
    <%= link_to "Detail", access_detail_report_links_path(@link), class: "btn btn-warning btn-sm mr-1" %>
    <%= button_to "Destroy this link", @link, method: :delete, class: "btn btn-danger mt-3",  onclick: "return confirm('Are you sure?');" %>
    <br>
    <%= link_to "Back to links", links_path, class: "btn btn-secondary" %>
</div>

app/views/main/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
<a class="navbar-brand" href="<%= root_path %>">chq.to</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if !user_signed_in? %>
          <li class="nav-item">
  					<%= link_to 'Sign up', new_user_registration_path, class: "nav-link"%>
          </li>

          <li class="nav-item">
  					<%= link_to 'Log in', new_user_session_path, class: "nav-link"%>
          </li>

      <% else %>
      <%= link_to "My Profile ", user_path(current_user), class: 'btn btn-outline-light' %>
      <%= link_to "My Links", links_path, class: 'btn btn-outline-light' %>
        <li class="nav-item">
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-outline-light' %>
        </li>
      <% end %>
  
    </ul>
  </div>
</nav>

app/views/main/home.html.erb
<% if current_user %>
  <div class="alert alert-success text-center mt-4" role="alert">
    <strong>Nice!</strong>
    <p>Hello, <%= current_user.username %>!</p>
  </div>
<% else %>
  <div class="jumbotron mt-4">
    <h1 class="display-4">Welcome to chq.to</h1>
    <hr class="my-4">
    <h2>If you don't have an account, you can sign up!</h2>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container mt-4">
  <h1 class="mb-4"><%= @user.username %>'s Profile</h1>

  <div class="card border-primary">
    <div class="card-header bg-primary text-white">
      <h5 class="mb-0">User Information</h5>
    </div>
    <div class="card-body">
      <p class="card-text"><strong>Username:</strong> <%= @user.username %></p>
      <p class="card-text"><strong>Email:</strong> <%= @user.email %></p>
    </div>
  </div>

  <%= link_to "Delete my account", edit_user_registration_path, method: :get, class: "btn btn-danger mt-3" %>
</div>